Portfolio set-up mobile first pull request
rachaouldbabaali/Portfolio-setup-and-mobile-first pull request #2
Opened 2023-03-23 09:30 UTC by rachaouldbabaali

2023-03-23 14:08 UTC, Ibizugbe requested changes
Hi @rachaouldbabaali 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/227228434-b2122c8d-395f-4e17-b6f6-bd9bd5b1b891.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Github flow practice has been used👍.
- [x] Linters are setup properly and they are passing👍.
- [x] The layouts for the content is done with flexbox👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Most of your commit messages look great but just a few of them are not capitalised😉 kindly ensure you capitalize your messages in future commit messages😉👍

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 14:08 UTC, Ibizugbe commented on index.html
> +            </section>
Nice job on creating your headline section😉 but try to stick to the given design😉 as this is a requirement for this milestone😎 kindly see the image comparison below😉

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="282" alt="your headline" src="https://user-images.githubusercontent.com/64643995/227227008-6ce52dc7-3596-49e4-9226-ef25e9b6a320.png" width="300">|![headline-mobile](https://user-images.githubusercontent.com/64643995/227227122-dca28ce1-718a-4918-abd4-00ed640ee0a7.png)|

Kindly take note of the `font-properties`  and the `spacings` and the `background image` and make the necessary change😉

2023-03-23 18:29 UTC, Kamba56 requested changes
Hi @rachaouldbabaali, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed!👏👏👏
- [ ] Great job using flexbox to layout contents

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 18:29 UTC, Kamba56 commented on index.html
> +      <section class="headline-section">
- [ ] Great job adding fonts and font sizes to match the design. As requested by the previous reviewer, kindly fix all spacings too to match the design template. You are expected to stick to design as much as possible.
### Your design
![image](https://user-images.githubusercontent.com/94551484/227311924-0aa9f993-c8fb-4149-a5f2-45eb06d9b3a1.png)
### Figma template
![image](https://user-images.githubusercontent.com/94551484/227312070-05ee8e51-cb96-4450-8e38-dd650638713a.png)

2023-03-23 18:29 UTC, Kamba56 commented on index.html
> +            </ul>
- [Optional] Kindly consider using an indentation of two spaces in all your documents. This is a best practice and also a convention.

2023-03-23 18:29 UTC, Kamba56 requested changes
Hi @rachaouldbabaali, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed!👏👏👏
- [ ] Great job using flexbox to layout contents

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 05:54 UTC, divinecharlotte approved these changes
# Hello @rachaouldbabaali       😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Descriptive PR ✔️
- Descriptive commit messages 👍 





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 16:27 UTC, closed without merging